# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('credits', models.IntegerField()),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('departament', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('rank', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Student')),
            ],
            options={
                'db_table': 'take',
            },
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Professor')),
            ],
            options={
                'db_table': 'teach',
            },
        ),
        migrations.AlterUniqueTogether(
            name='professor',
            unique_together=set([('first_name', 'last_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='teach',
            unique_together=set([('professor', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='take',
            unique_together=set([('student', 'course')]),
        ),
    ]
